export const apiUrl = process.env.NODE_ENV !== 'production' ? 'http://localhost:8080' : 'sth';

export const LOCAL_STORAGE_TOKEN_NAME = 'access-token';

export const SET_AUTH = 'SET_AUTH';

export const MY_PRODUCT_LOADED_SUCCESS = 'MY_PRODUCT_LOADED_SUCCESS';
export const MY_PRODUCT_LOADED_FAIL = 'MY_PRODUCT_LOADED_FAIL';
export const ALL_PRODUCT_LOADED_SUCCESS = 'ALL_PRODUCT_LOADED_SUCCESS';
export const ALL_PRODUCT_LOADED_FAIL = 'ALL_PRODUCT_LOADED_FAIL';

export const MY_BUY_TRANSACTION_LOADED_SUCCESS = 'MY_BUY_TRANSACTION_LOADED_SUCCESS'
export const MY_BUY_TRANSACTION_LOADED_FAIL = 'MY_BUY_TRANSACTION_LOADED_FAIL'
export const MY_SELL_TRANSACTION_LOADED_SUCCESS = 'MY_SELL_TRANSACTION_LOADED_SUCCESS'
export const MY_SELL_TRANSACTION_LOADED_FAIL = 'MY_SELL_TRANSACTION_LOADED_FAIL'
